### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by xcplus** [abhidiwakar/nextauth#1]
I download the code, and change nothing, then run the project by 'pnpm run dev' command and enter the correct email and password, but can't login. but my roommate can login in on his computer. 

---------------------
**I found the solution. upgrade node from 18.1.0 to 20.2.0**

**Comment by abhidiwakar** [comment]
Hi @xcplus,

Thank you for watching my video and trying out the code! I'm glad to hear that you found a solution to the login issue you were experiencing. Upgrading your Node version from 18.1.0 to 20.2.0 seems to have done the trick.

I wanted to mention that I created the project using Node.js version 20.0.0.

It's always great to see that my videos are helpful to people like you. Feel free to reach out if you have any more questions or need further assistance.
